//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco.CodeGen.Models
{
    using System;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using Umbraco.Core.Models;
    using Umbraco.Web;
    
    [DisplayName("Inherited Media Folder")]
    [Description("")]
    public partial class InheritedMediaFolder : Folder
    {
        #region Info members
        const String icon = "folder.gif";
        const String thumbnail = "folder.png";
        const Boolean allowAtRoot = true;
        private Type[] structure = new Type[] {
                typeof(Folder),
                typeof(Image),
                typeof(File),
                typeof(InheritedMediaFolder)};
        #endregion
        public InheritedMediaFolder(IPublishedContent content) : 
                base(content)
        {
        }
        [DisplayName("LetsHaveAProperty")]
        [Description("")]
        [Category("A tab")]
        [DataType("0cc0eba1-9960-42c9-bf9b-60e150b429ae")]
        public String LetsHaveAProperty
        {
            get
            {
                return Content.GetPropertyValue<String>("letsHaveAProperty");
            }
        }
        [DisplayName("And a tabless property")]
        [Description("")]
        [Category("")]
        [DataType("0cc0eba1-9960-42c9-bf9b-60e150b429ae")]
        public String AndATablessProperty
        {
            get
            {
                return Content.GetPropertyValue<String>("andATablessProperty");
            }
        }
    }
}
