//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco.CodeGen.Models
{
    using System;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using Umbraco.Core.Models;
    using Umbraco.Web;
    
    [DisplayName("Some document type")]
    [Description("A description of some document type")]
    public partial class SomeDocumentType : DocumentTypeBase
    {
        #region Info members
        const String icon = "privateMemberIcon.gif";
        const String thumbnail = "privateMemberThumb.png";
        const Boolean allowAtRoot = true;
        private String[] allowedTemplates = new String[] {
                "ATemplate",
                "AnotherTemplate"};
        const String defaultTemplate = "ATemplate";
        private Type[] structure = new Type[] {
                typeof(SomeOtherDocType)};
        #endregion
        public SomeDocumentType(IPublishedContent content) : 
                base(content)
        {
        }
        [DisplayName("Some property")]
        [Description("A description")]
        [Category("A tab")]
        [DataType("ca90c950-0aff-4e72-b976-a30b1ac57dad")]
        [RegularExpression("[a-z]")]
        [Required()]
        public String SomeProperty
        {
            get
            {
                return Content.GetPropertyValue<String>("someProperty");
            }
        }
        [DisplayName("Another property")]
        [Description("Another description")]
        [Category("A tab")]
        [DataType("ca90c950-0aff-4e72-b976-a30b1ac57dad")]
        public String AnotherProperty
        {
            get
            {
                return Content.GetPropertyValue<String>("anotherProperty");
            }
        }
        [DisplayName("Tabless property")]
        [Description("")]
        [Category("")]
        [DataType("2e6d3631-066e-44b8-aec4-96f09099b2b5")]
        public Int32 TablessProperty
        {
            get
            {
                return Content.GetPropertyValue<Int32>("tablessProperty");
            }
        }
    }
}
