//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco.CodeGen.Models
{
    using System;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using Umbraco.Core.Models;
    using Umbraco.Web;
    
    [Description("A description of some document type")]
    public class SomeDocumentType : DocumentTypeBase
    {
        private string icon = "privateMemberIcon.gif";
        private string thumbnail = "privateMemberThumb.png";
        private bool allowAtRoot = true;
        private string defaultTemplate = "ATemplate";
        private string[] allowedTemplates = new string[] {
                "ATemplate",
                "AnotherTemplate"};
        private System.Type[] structure = new System.Type[] {
                typeof(SomeOtherDocType)};
        [Description("A description")]
        [DataType("RTE")]
        [Category("A tab")]
        [Required()]
        [RegularExpression("[a-z]")]
        private String SomeProperty
        {
            get
            {
                return Content.GetPropertyValue<String>("someProperty");
            }
        }
        [Description("Another description")]
        [DataType("RTE")]
        [Category("A tab")]
        private String AnotherProperty
        {
            get
            {
                return Content.GetPropertyValue<String>("anotherProperty");
            }
        }
        [DataType("Numeric")]
        private Int32 TablessProperty
        {
            get
            {
                return Content.GetPropertyValue<Int32>("tablessProperty");
            }
        }
    }
}
